### ISSUE TITLE
Memory Error crash

### ISSUE THREAD

**Issue by 9swampy** [seeebek/EliteOCR#18]
My screens aren't very high res so F10 screenies don't OCR very well. Hence I try alt-f10 screen shots out generating 83 meg files, but when I attempt to OCR them I get (every time):

Traceback (most recent call last):
  File "<string>", line 175, in addFiles
  File "<string>", line 228, in selectFile
  File "C:\Users\SEBAST~1\Desktop\elite\RFACTO~1\build\EliteOCR\out00-PYZ.pyz\cu
stomqlistwidgetitem", line 33, in loadPreviewImage
  File "C:\Users\SEBAST~1\Desktop\elite\RFACTO~1\build\EliteOCR\out00-PYZ.pyz\cu
stomqlistwidgetitem", line 54, in addPreviewImage
  File "C:\Users\SEBAST~1\Desktop\elite\RFACTO~1\build\EliteOCR\out00-PYZ.pyz\oc
rmethods", line 18, in __init__
  File "C:\Users\SEBAST~1\Desktop\elite\RFACTO~1\build\EliteOCR\out00-PYZ.pyz\oc
rmethods", line 42, in findAreas
MemoryError

Any suggestions?

**Comment by seeebek** [comment]
It is clearly stated not to use ALT+F10 Screenshots with EliteOCR. 
Those are reducing the OCR accuracy even more than low res screenshots. Do not report this as a bug again as there is no memory leak. It is a result of having too little RAM and too big (unwanted) picture.

**Comment by 9swampy** [comment]
Thx for the answer and your well received work, though it's a pity as it means it doesn't seem to be working for me. I'll keep trying...

**Comment by seeebek** [comment]
Try the newest version
